stages:
    - EnsureContainer
    - BuildContainer
    - test

EnsureContainer:
    image: docker:latest
    services:
        - docker:dind
    stage: EnsureContainer
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
          when: always
        - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "dev"'
          when: always
    script:
        - "mkdir -p ~/.docker && echo '{\"experimental\": \"enabled\"}' > ~/.docker/config.json"
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker manifest inspect $CI_REGISTRY_IMAGE:all

BuildContainer:
    stage: BuildContainer
    image: docker:latest
    services:
        - docker:dind
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
          when: on_failure
        - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "dev"'
          when: on_failure
    script:
        - cd scripts/
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:all || true
        - docker build --cache-from $CI_REGISTRY_IMAGE:all -t $CI_REGISTRY_IMAGE:all .
        - docker push $CI_REGISTRY_IMAGE:all

test:
    stage: test
    image: $CI_REGISTRY_IMAGE:all
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
          when: always
        - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "dev"'
          when: always
    script:
        - mkdir -p engine/build || true
        - cd engine/build
        - conan install .. --build=missing --profile=debug
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
        - cmake --build . --target tests
        - ./bin/tests
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - "engine/build/__tests__/googletest-src"
